FROM ubuntu
RUN apt-get update && apt-get install -y postgresql-client
RUN apt-get update && apt-get install -y mysql-client
RUN apt-get update && apt-get install -y curl netcat

EXPOSE 2201

RUN mkdir /.aptible/

RUN echo "cyral_psql_client: nc -lk -p 2201" > /.aptible/Procfile
